version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    groups:
      patch-minor:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Moscow"
    groups:
      actions-patch-minor:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "github-actions"
