server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-json-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-json-logs
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            msg: msg
            requestId: requestId
      - labels:
          level:
